- name: Copy login.png
  copy:
    src: files/login.png
    dest: /proaluno/login.png
    mode: '0755'

- name: Copy lightdm-gtk-greeter.conf
  copy:
    src: files/lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    mode: '0644'

- name: Copy /etc/lightdm/lightdm.conf
  copy:
    src: files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    mode: '0644'
